title: Aaryan Chhabra
logo: /Images/Port_circular.png
description: "

Hello ðŸ‘‹ I'm Aaryan. My passion lies in geneticsðŸ§¬, genomics, computational biology, and bioinformatics. I'm constantly learning and excited by the latest advancements in these fields. Beyond the lab, I love traveling, hiking, and exploring new cultures. I'm also a tech enthusiast who enjoys trying out the latest gadgets. Join me as I explore the fascinating intersection of biology and technology!"
theme: jekyll-theme-minimal
